apiVersion: apps/v1
kind: Deployment
metadata:
  name: fullstack-deployment
  labels:
    app: fullstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fullstack
  template:
    metadata:
      labels:
        app: fullstack
    spec:
      containers:
        - name: backend
          image: shivam193/backend-app:latest
          ports:
            - containerPort: 5000
        - name: frontend
          image: shivam193/frontend-app:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: fullstack-backend-service
spec:
  selector:
    app: fullstack
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: fullstack-frontend-service
spec:
  selector:
    app: fullstack
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
